source: "/home/darth/Downloads/"
pdf: "/home/darth/the-duat/Inbox/Documents"
docx: "/home/darth/the-duat/Inbox/Documents"
xlsx: "/home/darth/the-duat/Inbox/Documents"
pptx: "/home/darth/the-duat/Inbox/Documents"
txt: "/home/darth/the-duat/Inbox/Text"
csv: "/home/darth/the-duat/Inbox/Text"
jpg: "/home/darth/the-duat/Inbox/Images"
jpeg: "/home/darth/the-duat/Inbox/Images"
png: "/home/darth/the-duat/Inbox/Images"
svg: "/home/darth/the-duat/Inbox/Images"
zip: "/home/darth/the-duat/Inbox/Archives"
rar: "/home/darth/the-duat/Inbox/Archives"
tar: "/home/darth/the-duat/Inbox/Archives"
mp3: "/home/darth/the-duat/Inbox/Videos"
mp4: "/home/darth/the-duat/Inbox/Videos"
mkv: "/home/darth/the-duat/Inbox/Videos"
other: "/home/darth/the-duat/Inbox/Other"
directory: "/home/darth/the-duat/Inbox/Folders"
